# Generated by Django 4.1.2 on 2022-11-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile.jpg', null=True, upload_to=''),
        ),
    ]
