# Generated by Django 4.1.2 on 2022-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='images'),
        ),
    ]
