# Generated by Django 4.1.2 on 2022-11-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='image',
        ),
    ]
