# Generated by Django 4.1.2 on 2022-11-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
