# Generated by Django 4.1.2 on 2022-11-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
